# https://github.com/elastic/kibana-docker
FROM docker.elastic.co/kibana/kibana-oss:6.2.2

# Add your kibana plugins setup here
# RUN kibana-plugin install x-pack

COPY config/kibana.yml /usr/share/kibana/config/kibana.yml
