# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2

# Add your elasticsearch plugins setup here
# RUN elasticsearch-plugin install x-pack

COPY config/elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml
